translations/ui-plugin-find-import-profile/ar.json, translations/ui-plugin-find-import-profile/ca.json, translations/ui-plugin-find-import-profile/da.json, translations/ui-plugin-find-import-profile/de.json, translations/ui-plugin-find-import-profile/en_GB.json, translations/ui-plugin-find-import-profile/en_SE.json, translations/ui-plugin-find-import-profile/en_US.json, translations/ui-plugin-find-import-profile/es.json, translations/ui-plugin-find-import-profile/es_419.json, translations/ui-plugin-find-import-profile/es_ES.json, translations/ui-plugin-find-import-profile/fr.json, translations/ui-plugin-find-import-profile/fr_FR.json, translations/ui-plugin-find-import-profile/hu.json, translations/ui-plugin-find-import-profile/it_IT.json, translations/ui-plugin-find-import-profile/ja.json, translations/ui-plugin-find-import-profile/pt_BR.json, translations/ui-plugin-find-import-profile/pt_PT.json, translations/ui-plugin-find-import-profile/ru.json, translations/ui-plugin-find-import-profile/zh_CN.json, translations/ui-plugin-find-import-profile/zh_TW.json
=> Update translation strings as of 20191111T233434

translations/ui-plugin-find-import-profile/it_IT.json
=> Update translation strings as of 20191112T144117

translations/ui-plugin-find-import-profile/he.json
=> Update translation strings as of 20191113T214202

translations/ui-plugin-find-import-profile/fr_FR.json
=> Update translation strings as of 20191115T154823

translations/ui-plugin-find-import-profile/fr_FR.json, translations/ui-plugin-find-import-profile/it_IT.json
=> Update translation strings as of 20191122T140350

translations/ui-plugin-find-import-profile/fr_FR.json
=> Update translation strings as of 20191127T181804

Jenkinsfile, package.json
"okapiInterfaces": {
"data-import": "3.0",
"source-manager-job-executions": "1.0",
"data-import-converter-storage": "1.0"
},
=> Release v1.1.0: Fix backend dependencies

translations/ui-plugin-find-import-profile/zh_CN.json
=> Update translation strings as of 20200109T152437

translations/ui-plugin-find-import-profile/fr_FR.json
=> Update translation strings as of 20200117T173544

translations/ui-plugin-find-import-profile/fr_FR.json
=> Update translation strings as of 20200127T144839

translations/ui-plugin-find-import-profile/fr_FR.json
=> Update translation strings as of 20200203T164535

translations/ui-plugin-find-import-profile/fr_FR.json
=> Update translation strings as of 20200217T172736

translations/ui-plugin-find-import-profile/ar.json
=> Update translation strings as of 20200224T151433

translations/ui-plugin-find-import-profile/fr_FR.json, translations/ui-plugin-find-import-profile/zh_CN.json
=> Update translation strings as of 20200302T163727

translations/ui-plugin-find-import-profile/pt_BR.json
=> Update translation strings as of 20200309T000645

translations/ui-plugin-find-import-profile/zh_TW.json
=> Update translation strings as of 20200424T193712

CHANGELOG.md, package.json
[UIPFIMP-18](https://issues.folio.org/browse/UIPFIMP-18)
=> UIPFIMP-18: Update to Stripes v4

CHANGELOG.md, FindImportProfile/FindImportProfileContainer/ActionProfilesContainer.js, FindImportProfile/FindImportProfileContainer/JobProfilesContainer.js, FindImportProfile/FindImportProfileContainer/MappingProfilesContainer.js, FindImportProfile/FindImportProfileContainer/MatchProfilesContainer.js, package.json, test/bigtest/helpers/appInit.js, test/bigtest/interactors/findImportProfileInteractor.js, test/bigtest/tests/findImportProfiles.e2e.js, test/bigtest/tests/findImportProfilesSingleSelect.e2e.js
[UIPFIMP-19](https://issues.folio.org/browse/UIPFIMP-19)
=> Release v2.0.0

translations/ui-plugin-find-import-profile/ru.json
=> Update translation strings as of 20200623T182030

CHANGELOG.md, package.json
Handle import of stripes-acq-components to modules and platform
https://issues.folio.org/browse/UISACQCOMP-3
=> UISACQCOMP-3 introduce stripes deps

translations/ui-plugin-find-import-profile/ar.json
=> Update translation strings as of 20200930T202600

translations/ui-plugin-find-import-profile/ja.json
=> Update translation strings as of 20201102T140138

translations/ui-plugin-find-import-profile/ber.json
=> Update translation strings as of 20201109T135508

CHANGELOG.md, package.json
To update stripes to v6
- Update dependencies in package.json 
https://issues.folio.org/browse/UIPFIMP-29
=> UIPFIMP-29 Update stripes to v6

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIPFIMP-32
=> UIPFIMP-32 - Update stripes-cli to v2

CHANGELOG.md, FindImportProfile/FindImportProfile.js, package.json
Refs
https://issues.folio.org/browse/UIPFIMP-37
=> UIPFIMP-37: refactor away from react-intl-safe-html

CHANGELOG.md, FindImportProfile/FindImportProfile.js, translations/ui-plugin-find-import-profile/en.json
To prevent users from attaching an action profile to a job profile if the action profile does not have an associated field mapping profile
- Check the associations when parentType is a Job profile
- Show confirmation modal when an action is not attached to a mapping profile
https://issues.folio.org/browse/UIDATIMP-990
=> UIDATIMP-990: Validate action profile has a field mapping profile before attaching to job profile

CHANGELOG.md, FindImportProfile/FindImportProfile.js
[UIDATIMP-1301](https://issues.folio.org/browse/UIDATIMP-1301)
=> UIPFIMP-53: Change imports for ListTemplate component in ui-plugin-find-import-profile
